//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap(Locale.init) ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: R.Class.self)
  
  static func validate() throws {
    try font.validate()
    try intern.validate()
  }
  
  /// This `R.color` struct is generated, and contains static references to 22 colors.
  struct color {
    /// Color `BottomBackgroundColor`.
    static let bottomBackgroundColor = Rswift.ColorResource(bundle: R.hostingBundle, name: "BottomBackgroundColor")
    /// Color `PokeBlack`.
    static let pokeBlack = Rswift.ColorResource(bundle: R.hostingBundle, name: "PokeBlack")
    /// Color `PokeRed`.
    static let pokeRed = Rswift.ColorResource(bundle: R.hostingBundle, name: "PokeRed")
    /// Color `TopBackgroundColor`.
    static let topBackgroundColor = Rswift.ColorResource(bundle: R.hostingBundle, name: "TopBackgroundColor")
    /// Color `aku`.
    static let aku = Rswift.ColorResource(bundle: R.hostingBundle, name: "aku")
    /// Color `denki`.
    static let denki = Rswift.ColorResource(bundle: R.hostingBundle, name: "denki")
    /// Color `doku`.
    static let doku = Rswift.ColorResource(bundle: R.hostingBundle, name: "doku")
    /// Color `dragon`.
    static let dragon = Rswift.ColorResource(bundle: R.hostingBundle, name: "dragon")
    /// Color `esper`.
    static let esper = Rswift.ColorResource(bundle: R.hostingBundle, name: "esper")
    /// Color `fairy`.
    static let fairy = Rswift.ColorResource(bundle: R.hostingBundle, name: "fairy")
    /// Color `ghost`.
    static let ghost = Rswift.ColorResource(bundle: R.hostingBundle, name: "ghost")
    /// Color `hagane`.
    static let hagane = Rswift.ColorResource(bundle: R.hostingBundle, name: "hagane")
    /// Color `hikou`.
    static let hikou = Rswift.ColorResource(bundle: R.hostingBundle, name: "hikou")
    /// Color `hono`.
    static let hono = Rswift.ColorResource(bundle: R.hostingBundle, name: "hono")
    /// Color `iwa`.
    static let iwa = Rswift.ColorResource(bundle: R.hostingBundle, name: "iwa")
    /// Color `jimen`.
    static let jimen = Rswift.ColorResource(bundle: R.hostingBundle, name: "jimen")
    /// Color `kakutou`.
    static let kakutou = Rswift.ColorResource(bundle: R.hostingBundle, name: "kakutou")
    /// Color `koori`.
    static let koori = Rswift.ColorResource(bundle: R.hostingBundle, name: "koori")
    /// Color `kusa`.
    static let kusa = Rswift.ColorResource(bundle: R.hostingBundle, name: "kusa")
    /// Color `mizu`.
    static let mizu = Rswift.ColorResource(bundle: R.hostingBundle, name: "mizu")
    /// Color `musi`.
    static let musi = Rswift.ColorResource(bundle: R.hostingBundle, name: "musi")
    /// Color `normal`.
    static let normal = Rswift.ColorResource(bundle: R.hostingBundle, name: "normal")
    
    /// `UIColor(named: "BottomBackgroundColor", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func bottomBackgroundColor(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.bottomBackgroundColor, compatibleWith: traitCollection)
    }
    
    /// `UIColor(named: "PokeBlack", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func pokeBlack(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.pokeBlack, compatibleWith: traitCollection)
    }
    
    /// `UIColor(named: "PokeRed", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func pokeRed(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.pokeRed, compatibleWith: traitCollection)
    }
    
    /// `UIColor(named: "TopBackgroundColor", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func topBackgroundColor(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.topBackgroundColor, compatibleWith: traitCollection)
    }
    
    /// `UIColor(named: "aku", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func aku(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.aku, compatibleWith: traitCollection)
    }
    
    /// `UIColor(named: "denki", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func denki(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.denki, compatibleWith: traitCollection)
    }
    
    /// `UIColor(named: "doku", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func doku(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.doku, compatibleWith: traitCollection)
    }
    
    /// `UIColor(named: "dragon", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func dragon(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.dragon, compatibleWith: traitCollection)
    }
    
    /// `UIColor(named: "esper", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func esper(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.esper, compatibleWith: traitCollection)
    }
    
    /// `UIColor(named: "fairy", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func fairy(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.fairy, compatibleWith: traitCollection)
    }
    
    /// `UIColor(named: "ghost", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func ghost(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.ghost, compatibleWith: traitCollection)
    }
    
    /// `UIColor(named: "hagane", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func hagane(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.hagane, compatibleWith: traitCollection)
    }
    
    /// `UIColor(named: "hikou", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func hikou(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.hikou, compatibleWith: traitCollection)
    }
    
    /// `UIColor(named: "hono", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func hono(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.hono, compatibleWith: traitCollection)
    }
    
    /// `UIColor(named: "iwa", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func iwa(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.iwa, compatibleWith: traitCollection)
    }
    
    /// `UIColor(named: "jimen", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func jimen(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.jimen, compatibleWith: traitCollection)
    }
    
    /// `UIColor(named: "kakutou", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func kakutou(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.kakutou, compatibleWith: traitCollection)
    }
    
    /// `UIColor(named: "koori", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func koori(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.koori, compatibleWith: traitCollection)
    }
    
    /// `UIColor(named: "kusa", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func kusa(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.kusa, compatibleWith: traitCollection)
    }
    
    /// `UIColor(named: "mizu", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func mizu(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.mizu, compatibleWith: traitCollection)
    }
    
    /// `UIColor(named: "musi", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func musi(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.musi, compatibleWith: traitCollection)
    }
    
    /// `UIColor(named: "normal", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func normal(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.normal, compatibleWith: traitCollection)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.file` struct is generated, and contains static references to 1 files.
  struct file {
    /// Resource file `GoogleService-Info.plist`.
    static let googleServiceInfoPlist = Rswift.FileResource(bundle: R.hostingBundle, name: "GoogleService-Info", pathExtension: "plist")
    
    /// `bundle.url(forResource: "GoogleService-Info", withExtension: "plist")`
    static func googleServiceInfoPlist(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.googleServiceInfoPlist
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.font` struct is generated, and contains static references to 1 fonts.
  struct font: Rswift.Validatable {
    /// Font `Tanuki-Permanent-Marker`.
    static let tanukiPermanentMarker = Rswift.FontResource(fontName: "Tanuki-Permanent-Marker")
    
    /// `UIFont(name: "Tanuki-Permanent-Marker", size: ...)`
    static func tanukiPermanentMarker(size: CGFloat) -> UIKit.UIFont? {
      return UIKit.UIFont(resource: tanukiPermanentMarker, size: size)
    }
    
    static func validate() throws {
      if R.font.tanukiPermanentMarker(size: 42) == nil { throw Rswift.ValidationError(description:"[R.swift] Font 'Tanuki-Permanent-Marker' could not be loaded, is 'TanukiMagic.ttf' added to the UIAppFonts array in this targets Info.plist?") }
    }
    
    fileprivate init() {}
  }
  
  /// This `R.image` struct is generated, and contains static references to 2 images.
  struct image {
    /// Image `Compatibility`.
    static let compatibility = Rswift.ImageResource(bundle: R.hostingBundle, name: "Compatibility")
    /// Image `splash`.
    static let splash = Rswift.ImageResource(bundle: R.hostingBundle, name: "splash")
    
    /// `UIImage(named: "Compatibility", bundle: ..., traitCollection: ...)`
    static func compatibility(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.compatibility, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "splash", bundle: ..., traitCollection: ...)`
    static func splash(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.splash, compatibleWith: traitCollection)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.reuseIdentifier` struct is generated, and contains static references to 4 reuse identifiers.
  struct reuseIdentifier {
    /// Reuse identifier `Header`.
    static let header: Rswift.ReuseIdentifier<HeaderTableViewCell> = Rswift.ReuseIdentifier(identifier: "Header")
    /// Reuse identifier `RankingTableViewCell`.
    static let rankingTableViewCell: Rswift.ReuseIdentifier<RankingTableViewCell> = Rswift.ReuseIdentifier(identifier: "RankingTableViewCell")
    /// Reuse identifier `SelectTypeCollectionViewCell`.
    static let selectTypeCollectionViewCell: Rswift.ReuseIdentifier<SelectTypeCollectionViewCell> = Rswift.ReuseIdentifier(identifier: "SelectTypeCollectionViewCell")
    /// Reuse identifier `TypeTableViewCell`.
    static let typeTableViewCell: Rswift.ReuseIdentifier<TypeTableViewCell> = Rswift.ReuseIdentifier(identifier: "TypeTableViewCell")
    
    fileprivate init() {}
  }
  
  /// This `R.storyboard` struct is generated, and contains static references to 2 storyboards.
  struct storyboard {
    /// Storyboard `LaunchScreen`.
    static let launchScreen = _R.storyboard.launchScreen()
    /// Storyboard `Main`.
    static let main = _R.storyboard.main()
    
    /// `UIStoryboard(name: "LaunchScreen", bundle: ...)`
    static func launchScreen(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.launchScreen)
    }
    
    /// `UIStoryboard(name: "Main", bundle: ...)`
    static func main(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.main)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.string` struct is generated, and contains static references to 3 localization tables.
  struct string {
    /// This `R.string.launchScreen` struct is generated, and contains static references to 0 localization keys.
    struct launchScreen {
      fileprivate init() {}
    }
    
    /// This `R.string.localizable` struct is generated, and contains static references to 33 localization keys.
    struct localizable {
      /// en translation: %
      /// 
      /// Locales: en, ja
      static let percent = Rswift.StringResource(key: "percent", tableName: "localizable", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: AccuracyRate：%.1f
      /// 
      /// Locales: en, ja
      static let accuracy_rate = Rswift.StringResource(key: "accuracy_rate", tableName: "localizable", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: BUG
      /// 
      /// Locales: en, ja
      static let musi = Rswift.StringResource(key: "musi", tableName: "localizable", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: Bad
      /// 
      /// Locales: en, ja
      static let bad = Rswift.StringResource(key: "bad", tableName: "localizable", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: Cencel
      /// 
      /// Locales: en, ja
      static let cancel = Rswift.StringResource(key: "cancel", tableName: "localizable", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: CompatibilityTable
      /// 
      /// Locales: en, ja
      static let compatibility_table = Rswift.StringResource(key: "compatibility_table", tableName: "localizable", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: Confirmation
      /// 
      /// Locales: en, ja
      static let confirmation = Rswift.StringResource(key: "confirmation", tableName: "localizable", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: DARK
      /// 
      /// Locales: en, ja
      static let aku = Rswift.StringResource(key: "aku", tableName: "localizable", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: DRAGON
      /// 
      /// Locales: en, ja
      static let dragon = Rswift.StringResource(key: "dragon", tableName: "localizable", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: ELECTRIC
      /// 
      /// Locales: en, ja
      static let denki = Rswift.StringResource(key: "denki", tableName: "localizable", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: Enemy attributes are displayed
      /// 
      /// Locales: en, ja
      static let quizLabel_tutorial = Rswift.StringResource(key: "quizLabel_tutorial", tableName: "localizable", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: FAIRY
      /// 
      /// Locales: en, ja
      static let fairy = Rswift.StringResource(key: "fairy", tableName: "localizable", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: FIGHTING
      /// 
      /// Locales: en, ja
      static let kakutou = Rswift.StringResource(key: "kakutou", tableName: "localizable", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: FIRE
      /// 
      /// Locales: en, ja
      static let hono = Rswift.StringResource(key: "hono", tableName: "localizable", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: FLYING
      /// 
      /// Locales: en, ja
      static let hikou = Rswift.StringResource(key: "hikou", tableName: "localizable", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: GHOST
      /// 
      /// Locales: en, ja
      static let ghost = Rswift.StringResource(key: "ghost", tableName: "localizable", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: GRASS
      /// 
      /// Locales: en, ja
      static let kusa = Rswift.StringResource(key: "kusa", tableName: "localizable", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: GROUND
      /// 
      /// Locales: en, ja
      static let jimen = Rswift.StringResource(key: "jimen", tableName: "localizable", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: Good
      /// 
      /// Locales: en, ja
      static let good = Rswift.StringResource(key: "good", tableName: "localizable", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: ICE
      /// 
      /// Locales: en, ja
      static let koori = Rswift.StringResource(key: "koori", tableName: "localizable", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: If you make a mistake 4 times, the game is over!
      /// 
      /// Locales: en, ja
      static let lifeImages_tutorial = Rswift.StringResource(key: "lifeImages_tutorial", tableName: "localizable", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: Let's choose all the attributes with outstanding effects!
      /// 
      /// Locales: en, ja
      static let selectTypeCollectionView_tutorial = Rswift.StringResource(key: "selectTypeCollectionView_tutorial", tableName: "localizable", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: NORMAL
      /// 
      /// Locales: en, ja
      static let normal = Rswift.StringResource(key: "normal", tableName: "localizable", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: OK
      /// 
      /// Locales: en, ja
      static let ok = Rswift.StringResource(key: "ok", tableName: "localizable", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: Open the reference URL in Safari
      /// 
      /// Locales: en, ja
      static let open_the_reference_URL_in_Safari = Rswift.StringResource(key: "open_the_reference_URL_in_Safari", tableName: "localizable", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: POISON
      /// 
      /// Locales: en, ja
      static let doku = Rswift.StringResource(key: "doku", tableName: "localizable", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: PSYCHIC
      /// 
      /// Locales: en, ja
      static let esper = Rswift.StringResource(key: "esper", tableName: "localizable", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: ROCK
      /// 
      /// Locales: en, ja
      static let iwa = Rswift.StringResource(key: "iwa", tableName: "localizable", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: Ranking
      /// 
      /// Locales: en, ja
      static let ranking = Rswift.StringResource(key: "ranking", tableName: "localizable", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: STEEL
      /// 
      /// Locales: en, ja
      static let hagane = Rswift.StringResource(key: "hagane", tableName: "localizable", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: Send Completely
      /// 
      /// Locales: en, ja
      static let send_complete = Rswift.StringResource(key: "send_complete", tableName: "localizable", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: This is excellent for %@
      /// 
      /// Locales: en, ja
      static let this_is_excellent_for = Rswift.StringResource(key: "This_is_excellent_for", tableName: "localizable", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      /// en translation: WATER
      /// 
      /// Locales: en, ja
      static let mizu = Rswift.StringResource(key: "mizu", tableName: "localizable", bundle: R.hostingBundle, locales: ["en", "ja"], comment: nil)
      
      /// en translation: %
      /// 
      /// Locales: en, ja
      static func percent(_: Void = ()) -> String {
        return NSLocalizedString("percent", tableName: "localizable", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: AccuracyRate：%.1f
      /// 
      /// Locales: en, ja
      static func accuracy_rate(_ value1: Double) -> String {
        return String(format: NSLocalizedString("accuracy_rate", tableName: "localizable", bundle: R.hostingBundle, comment: ""), locale: R.applicationLocale, value1)
      }
      
      /// en translation: BUG
      /// 
      /// Locales: en, ja
      static func musi(_: Void = ()) -> String {
        return NSLocalizedString("musi", tableName: "localizable", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: Bad
      /// 
      /// Locales: en, ja
      static func bad(_: Void = ()) -> String {
        return NSLocalizedString("bad", tableName: "localizable", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: Cencel
      /// 
      /// Locales: en, ja
      static func cancel(_: Void = ()) -> String {
        return NSLocalizedString("cancel", tableName: "localizable", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: CompatibilityTable
      /// 
      /// Locales: en, ja
      static func compatibility_table(_: Void = ()) -> String {
        return NSLocalizedString("compatibility_table", tableName: "localizable", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: Confirmation
      /// 
      /// Locales: en, ja
      static func confirmation(_: Void = ()) -> String {
        return NSLocalizedString("confirmation", tableName: "localizable", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: DARK
      /// 
      /// Locales: en, ja
      static func aku(_: Void = ()) -> String {
        return NSLocalizedString("aku", tableName: "localizable", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: DRAGON
      /// 
      /// Locales: en, ja
      static func dragon(_: Void = ()) -> String {
        return NSLocalizedString("dragon", tableName: "localizable", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: ELECTRIC
      /// 
      /// Locales: en, ja
      static func denki(_: Void = ()) -> String {
        return NSLocalizedString("denki", tableName: "localizable", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: Enemy attributes are displayed
      /// 
      /// Locales: en, ja
      static func quizLabel_tutorial(_: Void = ()) -> String {
        return NSLocalizedString("quizLabel_tutorial", tableName: "localizable", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: FAIRY
      /// 
      /// Locales: en, ja
      static func fairy(_: Void = ()) -> String {
        return NSLocalizedString("fairy", tableName: "localizable", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: FIGHTING
      /// 
      /// Locales: en, ja
      static func kakutou(_: Void = ()) -> String {
        return NSLocalizedString("kakutou", tableName: "localizable", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: FIRE
      /// 
      /// Locales: en, ja
      static func hono(_: Void = ()) -> String {
        return NSLocalizedString("hono", tableName: "localizable", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: FLYING
      /// 
      /// Locales: en, ja
      static func hikou(_: Void = ()) -> String {
        return NSLocalizedString("hikou", tableName: "localizable", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: GHOST
      /// 
      /// Locales: en, ja
      static func ghost(_: Void = ()) -> String {
        return NSLocalizedString("ghost", tableName: "localizable", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: GRASS
      /// 
      /// Locales: en, ja
      static func kusa(_: Void = ()) -> String {
        return NSLocalizedString("kusa", tableName: "localizable", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: GROUND
      /// 
      /// Locales: en, ja
      static func jimen(_: Void = ()) -> String {
        return NSLocalizedString("jimen", tableName: "localizable", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: Good
      /// 
      /// Locales: en, ja
      static func good(_: Void = ()) -> String {
        return NSLocalizedString("good", tableName: "localizable", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: ICE
      /// 
      /// Locales: en, ja
      static func koori(_: Void = ()) -> String {
        return NSLocalizedString("koori", tableName: "localizable", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: If you make a mistake 4 times, the game is over!
      /// 
      /// Locales: en, ja
      static func lifeImages_tutorial(_: Void = ()) -> String {
        return NSLocalizedString("lifeImages_tutorial", tableName: "localizable", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: Let's choose all the attributes with outstanding effects!
      /// 
      /// Locales: en, ja
      static func selectTypeCollectionView_tutorial(_: Void = ()) -> String {
        return NSLocalizedString("selectTypeCollectionView_tutorial", tableName: "localizable", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: NORMAL
      /// 
      /// Locales: en, ja
      static func normal(_: Void = ()) -> String {
        return NSLocalizedString("normal", tableName: "localizable", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: OK
      /// 
      /// Locales: en, ja
      static func ok(_: Void = ()) -> String {
        return NSLocalizedString("ok", tableName: "localizable", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: Open the reference URL in Safari
      /// 
      /// Locales: en, ja
      static func open_the_reference_URL_in_Safari(_: Void = ()) -> String {
        return NSLocalizedString("open_the_reference_URL_in_Safari", tableName: "localizable", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: POISON
      /// 
      /// Locales: en, ja
      static func doku(_: Void = ()) -> String {
        return NSLocalizedString("doku", tableName: "localizable", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: PSYCHIC
      /// 
      /// Locales: en, ja
      static func esper(_: Void = ()) -> String {
        return NSLocalizedString("esper", tableName: "localizable", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: ROCK
      /// 
      /// Locales: en, ja
      static func iwa(_: Void = ()) -> String {
        return NSLocalizedString("iwa", tableName: "localizable", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: Ranking
      /// 
      /// Locales: en, ja
      static func ranking(_: Void = ()) -> String {
        return NSLocalizedString("ranking", tableName: "localizable", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: STEEL
      /// 
      /// Locales: en, ja
      static func hagane(_: Void = ()) -> String {
        return NSLocalizedString("hagane", tableName: "localizable", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: Send Completely
      /// 
      /// Locales: en, ja
      static func send_complete(_: Void = ()) -> String {
        return NSLocalizedString("send_complete", tableName: "localizable", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: This is excellent for %@
      /// 
      /// Locales: en, ja
      static func this_is_excellent_for(_ value1: String) -> String {
        return String(format: NSLocalizedString("This_is_excellent_for", tableName: "localizable", bundle: R.hostingBundle, comment: ""), locale: R.applicationLocale, value1)
      }
      
      /// en translation: WATER
      /// 
      /// Locales: en, ja
      static func mizu(_: Void = ()) -> String {
        return NSLocalizedString("mizu", tableName: "localizable", bundle: R.hostingBundle, comment: "")
      }
      
      fileprivate init() {}
    }
    
    /// This `R.string.main` struct is generated, and contains static references to 27 localization keys.
    struct main {
      /// ja translation: --
      /// 
      /// Locales: ja
      static let qRxYY724Text = Rswift.StringResource(key: "qRx-yY-724.text", tableName: "Main", bundle: R.hostingBundle, locales: ["ja"], comment: nil)
      /// ja translation: Label
      /// 
      /// Locales: ja
      static let dIv86E3IText = Rswift.StringResource(key: "dIv-86-E3I.text", tableName: "Main", bundle: R.hostingBundle, locales: ["ja"], comment: nil)
      /// ja translation: Label
      /// 
      /// Locales: ja
      static let jZfX1XLeText = Rswift.StringResource(key: "JZf-x1-XLe.text", tableName: "Main", bundle: R.hostingBundle, locales: ["ja"], comment: nil)
      /// ja translation: Label
      /// 
      /// Locales: ja
      static let ntkCvHVjText = Rswift.StringResource(key: "ntk-cv-HVj.text", tableName: "Main", bundle: R.hostingBundle, locales: ["ja"], comment: nil)
      /// ja translation: Label
      /// 
      /// Locales: ja
      static let pV2RfBrfText = Rswift.StringResource(key: "pV2-rf-brf.text", tableName: "Main", bundle: R.hostingBundle, locales: ["ja"], comment: nil)
      /// ja translation: Label
      /// 
      /// Locales: ja
      static let pWJQVBbdText = Rswift.StringResource(key: "pWJ-QV-bbd.text", tableName: "Main", bundle: R.hostingBundle, locales: ["ja"], comment: nil)
      /// ja translation: Label
      /// 
      /// Locales: ja
      static let rzCKTDfText = Rswift.StringResource(key: "7rz-cK-tDf.text", tableName: "Main", bundle: R.hostingBundle, locales: ["ja"], comment: nil)
      /// ja translation: Question 0
      /// 
      /// Locales: ja
      static let jjDiZfdText = Rswift.StringResource(key: "9Jj-di-Zfd.text", tableName: "Main", bundle: R.hostingBundle, locales: ["ja"], comment: nil)
      /// ja translation: 〜ポケ相性問題アプリ〜
      /// 
      /// Locales: ja
      static let qPjPG7hnText = Rswift.StringResource(key: "QPj-PG-7hn.text", tableName: "Main", bundle: R.hostingBundle, locales: ["ja"], comment: nil)
      /// ja translation: ぽけくいず
      /// 
      /// Locales: ja
      static let okd7JJCbText = Rswift.StringResource(key: "okd-7J-JCb.text", tableName: "Main", bundle: R.hostingBundle, locales: ["ja"], comment: nil)
      /// ja translation: キャンセル
      /// 
      /// Locales: ja
      static let vVIDD7jNormalTitle = Rswift.StringResource(key: "5vV-ID-D7j.normalTitle", tableName: "Main", bundle: R.hostingBundle, locales: ["ja"], comment: nil)
      /// ja translation: クイズスタート
      /// 
      /// Locales: ja
      static let d2A6ER34NormalTitle = Rswift.StringResource(key: "d2A-6E-r34.normalTitle", tableName: "Main", bundle: R.hostingBundle, locales: ["ja"], comment: nil)
      /// ja translation: ポイント
      /// 
      /// Locales: ja
      static let nGfL9VTYText = Rswift.StringResource(key: "nGf-l9-VTY.text", tableName: "Main", bundle: R.hostingBundle, locales: ["ja"], comment: nil)
      /// ja translation: メニューへ
      /// 
      /// Locales: ja
      static let lB6U1F9YNormalTitle = Rswift.StringResource(key: "lB6-U1-F9Y.normalTitle", tableName: "Main", bundle: R.hostingBundle, locales: ["ja"], comment: nil)
      /// ja translation: ランキング
      /// 
      /// Locales: ja
      static let u82CHXOWNormalTitle = Rswift.StringResource(key: "U82-CH-xOW.normalTitle", tableName: "Main", bundle: R.hostingBundle, locales: ["ja"], comment: nil)
      /// ja translation: 今回のポイントは‥
      /// 
      /// Locales: ja
      static let v0DYpKxfText = Rswift.StringResource(key: "V0D-yp-Kxf.text", tableName: "Main", bundle: R.hostingBundle, locales: ["ja"], comment: nil)
      /// ja translation: 効果抜群を選べ！
      /// 
      /// Locales: ja
      static let tc8Vi1SPText = Rswift.StringResource(key: "tc8-Vi-1SP.text", tableName: "Main", bundle: R.hostingBundle, locales: ["ja"], comment: nil)
      /// ja translation: 参考元
      /// 
      /// Locales: ja
      static let kacIE6H7NormalTitle = Rswift.StringResource(key: "kac-IE-6H7.normalTitle", tableName: "Main", bundle: R.hostingBundle, locales: ["ja"], comment: nil)
      /// ja translation: 名前
      /// 
      /// Locales: ja
      static let elBP6Ug2Text = Rswift.StringResource(key: "elB-P6-Ug2.text", tableName: "Main", bundle: R.hostingBundle, locales: ["ja"], comment: nil)
      /// ja translation: 名前を入力
      /// 
      /// Locales: ja
      static let wyNSDL2Placeholder = Rswift.StringResource(key: "6Wy-nS-DL2.placeholder", tableName: "Main", bundle: R.hostingBundle, locales: ["ja"], comment: nil)
      /// ja translation: 名前を入力！
      /// 
      /// Locales: ja
      static let ha7L9NJRText = Rswift.StringResource(key: "ha7-l9-NJR.text", tableName: "Main", bundle: R.hostingBundle, locales: ["ja"], comment: nil)
      /// ja translation: 次へ
      /// 
      /// Locales: ja
      static let qh4GhG94NormalTitle = Rswift.StringResource(key: "qh4-gh-g94.normalTitle", tableName: "Main", bundle: R.hostingBundle, locales: ["ja"], comment: nil)
      /// ja translation: 決定
      /// 
      /// Locales: ja
      static let oqVgVLPNormalTitle = Rswift.StringResource(key: "5Oq-vg-VLP.normalTitle", tableName: "Main", bundle: R.hostingBundle, locales: ["ja"], comment: nil)
      /// ja translation: 相性表
      /// 
      /// Locales: ja
      static let zOpNy9dKNormalTitle = Rswift.StringResource(key: "ZOp-ny-9dK.normalTitle", tableName: "Main", bundle: R.hostingBundle, locales: ["ja"], comment: nil)
      /// ja translation: 結果をランキングへ投稿
      /// 
      /// Locales: ja
      static let oxJE4UdnNormalTitle = Rswift.StringResource(key: "oxJ-e4-Udn.normalTitle", tableName: "Main", bundle: R.hostingBundle, locales: ["ja"], comment: nil)
      /// ja translation: 送信
      /// 
      /// Locales: ja
      static let sQWsIxaNormalTitle = Rswift.StringResource(key: "5sQ-Ws-ixa.normalTitle", tableName: "Main", bundle: R.hostingBundle, locales: ["ja"], comment: nil)
      /// ja translation: 順位
      /// 
      /// Locales: ja
      static let cv6Ib06qText = Rswift.StringResource(key: "CV6-Ib-06q.text", tableName: "Main", bundle: R.hostingBundle, locales: ["ja"], comment: nil)
      
      /// ja translation: --
      /// 
      /// Locales: ja
      static func qRxYY724Text(_: Void = ()) -> String {
        return NSLocalizedString("qRx-yY-724.text", tableName: "Main", bundle: R.hostingBundle, comment: "")
      }
      
      /// ja translation: Label
      /// 
      /// Locales: ja
      static func dIv86E3IText(_: Void = ()) -> String {
        return NSLocalizedString("dIv-86-E3I.text", tableName: "Main", bundle: R.hostingBundle, comment: "")
      }
      
      /// ja translation: Label
      /// 
      /// Locales: ja
      static func jZfX1XLeText(_: Void = ()) -> String {
        return NSLocalizedString("JZf-x1-XLe.text", tableName: "Main", bundle: R.hostingBundle, comment: "")
      }
      
      /// ja translation: Label
      /// 
      /// Locales: ja
      static func ntkCvHVjText(_: Void = ()) -> String {
        return NSLocalizedString("ntk-cv-HVj.text", tableName: "Main", bundle: R.hostingBundle, comment: "")
      }
      
      /// ja translation: Label
      /// 
      /// Locales: ja
      static func pV2RfBrfText(_: Void = ()) -> String {
        return NSLocalizedString("pV2-rf-brf.text", tableName: "Main", bundle: R.hostingBundle, comment: "")
      }
      
      /// ja translation: Label
      /// 
      /// Locales: ja
      static func pWJQVBbdText(_: Void = ()) -> String {
        return NSLocalizedString("pWJ-QV-bbd.text", tableName: "Main", bundle: R.hostingBundle, comment: "")
      }
      
      /// ja translation: Label
      /// 
      /// Locales: ja
      static func rzCKTDfText(_: Void = ()) -> String {
        return NSLocalizedString("7rz-cK-tDf.text", tableName: "Main", bundle: R.hostingBundle, comment: "")
      }
      
      /// ja translation: Question 0
      /// 
      /// Locales: ja
      static func jjDiZfdText(_: Void = ()) -> String {
        return NSLocalizedString("9Jj-di-Zfd.text", tableName: "Main", bundle: R.hostingBundle, comment: "")
      }
      
      /// ja translation: 〜ポケ相性問題アプリ〜
      /// 
      /// Locales: ja
      static func qPjPG7hnText(_: Void = ()) -> String {
        return NSLocalizedString("QPj-PG-7hn.text", tableName: "Main", bundle: R.hostingBundle, comment: "")
      }
      
      /// ja translation: ぽけくいず
      /// 
      /// Locales: ja
      static func okd7JJCbText(_: Void = ()) -> String {
        return NSLocalizedString("okd-7J-JCb.text", tableName: "Main", bundle: R.hostingBundle, comment: "")
      }
      
      /// ja translation: キャンセル
      /// 
      /// Locales: ja
      static func vVIDD7jNormalTitle(_: Void = ()) -> String {
        return NSLocalizedString("5vV-ID-D7j.normalTitle", tableName: "Main", bundle: R.hostingBundle, comment: "")
      }
      
      /// ja translation: クイズスタート
      /// 
      /// Locales: ja
      static func d2A6ER34NormalTitle(_: Void = ()) -> String {
        return NSLocalizedString("d2A-6E-r34.normalTitle", tableName: "Main", bundle: R.hostingBundle, comment: "")
      }
      
      /// ja translation: ポイント
      /// 
      /// Locales: ja
      static func nGfL9VTYText(_: Void = ()) -> String {
        return NSLocalizedString("nGf-l9-VTY.text", tableName: "Main", bundle: R.hostingBundle, comment: "")
      }
      
      /// ja translation: メニューへ
      /// 
      /// Locales: ja
      static func lB6U1F9YNormalTitle(_: Void = ()) -> String {
        return NSLocalizedString("lB6-U1-F9Y.normalTitle", tableName: "Main", bundle: R.hostingBundle, comment: "")
      }
      
      /// ja translation: ランキング
      /// 
      /// Locales: ja
      static func u82CHXOWNormalTitle(_: Void = ()) -> String {
        return NSLocalizedString("U82-CH-xOW.normalTitle", tableName: "Main", bundle: R.hostingBundle, comment: "")
      }
      
      /// ja translation: 今回のポイントは‥
      /// 
      /// Locales: ja
      static func v0DYpKxfText(_: Void = ()) -> String {
        return NSLocalizedString("V0D-yp-Kxf.text", tableName: "Main", bundle: R.hostingBundle, comment: "")
      }
      
      /// ja translation: 効果抜群を選べ！
      /// 
      /// Locales: ja
      static func tc8Vi1SPText(_: Void = ()) -> String {
        return NSLocalizedString("tc8-Vi-1SP.text", tableName: "Main", bundle: R.hostingBundle, comment: "")
      }
      
      /// ja translation: 参考元
      /// 
      /// Locales: ja
      static func kacIE6H7NormalTitle(_: Void = ()) -> String {
        return NSLocalizedString("kac-IE-6H7.normalTitle", tableName: "Main", bundle: R.hostingBundle, comment: "")
      }
      
      /// ja translation: 名前
      /// 
      /// Locales: ja
      static func elBP6Ug2Text(_: Void = ()) -> String {
        return NSLocalizedString("elB-P6-Ug2.text", tableName: "Main", bundle: R.hostingBundle, comment: "")
      }
      
      /// ja translation: 名前を入力
      /// 
      /// Locales: ja
      static func wyNSDL2Placeholder(_: Void = ()) -> String {
        return NSLocalizedString("6Wy-nS-DL2.placeholder", tableName: "Main", bundle: R.hostingBundle, comment: "")
      }
      
      /// ja translation: 名前を入力！
      /// 
      /// Locales: ja
      static func ha7L9NJRText(_: Void = ()) -> String {
        return NSLocalizedString("ha7-l9-NJR.text", tableName: "Main", bundle: R.hostingBundle, comment: "")
      }
      
      /// ja translation: 次へ
      /// 
      /// Locales: ja
      static func qh4GhG94NormalTitle(_: Void = ()) -> String {
        return NSLocalizedString("qh4-gh-g94.normalTitle", tableName: "Main", bundle: R.hostingBundle, comment: "")
      }
      
      /// ja translation: 決定
      /// 
      /// Locales: ja
      static func oqVgVLPNormalTitle(_: Void = ()) -> String {
        return NSLocalizedString("5Oq-vg-VLP.normalTitle", tableName: "Main", bundle: R.hostingBundle, comment: "")
      }
      
      /// ja translation: 相性表
      /// 
      /// Locales: ja
      static func zOpNy9dKNormalTitle(_: Void = ()) -> String {
        return NSLocalizedString("ZOp-ny-9dK.normalTitle", tableName: "Main", bundle: R.hostingBundle, comment: "")
      }
      
      /// ja translation: 結果をランキングへ投稿
      /// 
      /// Locales: ja
      static func oxJE4UdnNormalTitle(_: Void = ()) -> String {
        return NSLocalizedString("oxJ-e4-Udn.normalTitle", tableName: "Main", bundle: R.hostingBundle, comment: "")
      }
      
      /// ja translation: 送信
      /// 
      /// Locales: ja
      static func sQWsIxaNormalTitle(_: Void = ()) -> String {
        return NSLocalizedString("5sQ-Ws-ixa.normalTitle", tableName: "Main", bundle: R.hostingBundle, comment: "")
      }
      
      /// ja translation: 順位
      /// 
      /// Locales: ja
      static func cv6Ib06qText(_: Void = ()) -> String {
        return NSLocalizedString("CV6-Ib-06q.text", tableName: "Main", bundle: R.hostingBundle, comment: "")
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      try _R.validate()
    }
    
    fileprivate init() {}
  }
  
  fileprivate class Class {}
  
  fileprivate init() {}
}

struct _R: Rswift.Validatable {
  static func validate() throws {
    try storyboard.validate()
  }
  
  struct storyboard: Rswift.Validatable {
    static func validate() throws {
      try launchScreen.validate()
      try main.validate()
    }
    
    struct launchScreen: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIKit.UIViewController
      
      let bundle = R.hostingBundle
      let name = "LaunchScreen"
      
      static func validate() throws {
        if #available(iOS 11.0, *) {
        }
      }
      
      fileprivate init() {}
    }
    
    struct main: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIKit.UINavigationController
      
      let bundle = R.hostingBundle
      let gameOverViewController = StoryboardViewControllerResource<GameOverViewController>(identifier: "GameOverViewController")
      let inputNameViewController = StoryboardViewControllerResource<InputNameViewController>(identifier: "InputNameViewController")
      let menuViewController = StoryboardViewControllerResource<MenuViewController>(identifier: "MenuViewController")
      let name = "Main"
      let quizViewController = StoryboardViewControllerResource<QuizViewController>(identifier: "QuizViewController")
      let rankingViewController = StoryboardViewControllerResource<RankingViewController>(identifier: "RankingViewController")
      let resultViewController = StoryboardViewControllerResource<ResultViewController>(identifier: "ResultViewController")
      
      func gameOverViewController(_: Void = ()) -> GameOverViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: gameOverViewController)
      }
      
      func inputNameViewController(_: Void = ()) -> InputNameViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: inputNameViewController)
      }
      
      func menuViewController(_: Void = ()) -> MenuViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: menuViewController)
      }
      
      func quizViewController(_: Void = ()) -> QuizViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: quizViewController)
      }
      
      func rankingViewController(_: Void = ()) -> RankingViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: rankingViewController)
      }
      
      func resultViewController(_: Void = ()) -> ResultViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: resultViewController)
      }
      
      static func validate() throws {
        if UIKit.UIImage(named: "heart.fill", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'heart.fill' is used in storyboard 'Main', but couldn't be loaded.") }
        if #available(iOS 11.0, *) {
          if UIKit.UIColor(named: "BottomBackgroundColor", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Color named 'BottomBackgroundColor' is used in storyboard 'Main', but couldn't be loaded.") }
          if UIKit.UIColor(named: "PokeBlack", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Color named 'PokeBlack' is used in storyboard 'Main', but couldn't be loaded.") }
          if UIKit.UIColor(named: "PokeRed", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Color named 'PokeRed' is used in storyboard 'Main', but couldn't be loaded.") }
          if UIKit.UIColor(named: "TopBackgroundColor", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Color named 'TopBackgroundColor' is used in storyboard 'Main', but couldn't be loaded.") }
          if UIKit.UIColor(named: "denki", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Color named 'denki' is used in storyboard 'Main', but couldn't be loaded.") }
          if UIKit.UIColor(named: "hikou", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Color named 'hikou' is used in storyboard 'Main', but couldn't be loaded.") }
          if UIKit.UIColor(named: "hono", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Color named 'hono' is used in storyboard 'Main', but couldn't be loaded.") }
          if UIKit.UIColor(named: "jimen", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Color named 'jimen' is used in storyboard 'Main', but couldn't be loaded.") }
          if UIKit.UIColor(named: "mizu", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Color named 'mizu' is used in storyboard 'Main', but couldn't be loaded.") }
        }
        if _R.storyboard.main().gameOverViewController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'gameOverViewController' could not be loaded from storyboard 'Main' as 'GameOverViewController'.") }
        if _R.storyboard.main().inputNameViewController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'inputNameViewController' could not be loaded from storyboard 'Main' as 'InputNameViewController'.") }
        if _R.storyboard.main().menuViewController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'menuViewController' could not be loaded from storyboard 'Main' as 'MenuViewController'.") }
        if _R.storyboard.main().quizViewController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'quizViewController' could not be loaded from storyboard 'Main' as 'QuizViewController'.") }
        if _R.storyboard.main().rankingViewController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'rankingViewController' could not be loaded from storyboard 'Main' as 'RankingViewController'.") }
        if _R.storyboard.main().resultViewController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'resultViewController' could not be loaded from storyboard 'Main' as 'ResultViewController'.") }
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  fileprivate init() {}
}
